[package]
name = "oj"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust-native build tool for React apps"

[[bin]]
name = "oj"
path = "src/main.rs"

[dependencies]
oj_cache.workspace = true
oj_compiler.workspace = true
oj_env.workspace = true
oj_config.workspace = true
oj_resolver.workspace = true
oj_server.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
rolldown = "1.2.5"
rolldown_common = "1.2.5"
rolldown_plugin = "1.2.5"
rolldown_utils = "1.2.5"
arcstr = "1.2.0"
serde_json.workspace = true
blake3.workspace = true
flate2 = "1"
oj_css.workspace = true
axum.workspace = true
notify.workspace = true
tokio-stream = "0.1.19"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full", "test-util"] }
