[workspace]
resolver = "2"
members = [
    "crates/oj_compiler",
    "crates/oj_css",
    "crates/oj_env",
    "crates/oj_config",
    "crates/oj_resolver",
    "crates/oj_graph",
    "crates/oj_cache",
    "crates/oj_server",
    "crates/oj",
]

[workspace.package]
version = "0.0.22"
edition = "2021"
license = "MIT"

[workspace.dependencies]
oj_compiler = { version = "0.0.22", path = "crates/oj_compiler" }
oj_resolver = { version = "0.0.22", path = "crates/oj_resolver" }
oj_graph = { version = "0.0.22", path = "crates/oj_graph" }
oj_cache = { version = "0.0.22", path = "crates/oj_cache" }
oj_css = { version = "0.0.22", path = "crates/oj_css" }
oj_env = { version = "0.0.22", path = "crates/oj_env" }
oj_config = { version = "0.0.22", path = "crates/oj_config" }
oj_server = { version = "0.0.22", path = "crates/oj_server" }

oxc_allocator = "0.144.0"
oxc_parser = "0.144.0"
oxc_ast = "0.144.0"
oxc_ast_visit = "0.144.0"
oxc_span = "0.144.0"
oxc_semantic = "0.144.0"
oxc_transformer = "0.144.0"
oxc_transformer_plugins = "0.144.0"
oxc_minifier = "0.144.0"
oxc_ecmascript = "0.144.0"
oxc_syntax = "0.144.0"
oxc_codegen = "0.144.0"
oxc_diagnostics = "0.144.0"
oxc_resolver = "11.24.2"

anyhow = "1.0.104"
blake3 = "1.8.6"
memchr = "2.8.3"
simdutf8 = "0.1.5"
thiserror = "2.0.20"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
axum = { version = "0.8.9", features = ["ws"] }
notify = "8.2.0"
clap = { version = "4.6.6", features = ["derive"] }

[profile.release]
lto = "thin"
codegen-units = 1
