// SPDX-License-Identifier: MIT
//
// CSS modules in SSR must evaluate to the same class-name map the client is
// served (css_exports from oj_css::compile_css_rebased, lightningcss pattern
// "[name]_[local]_[hash]"). The loader recomputes those names in JS; the
// expected literals here are pinned against the Rust side by
// css_modules_scoped_name_matches_ssr_loader in crates/oj_css.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const loader = resolve(here, "../../crates/oj_server/src/assets/start/loader.mjs");

test("SSR loader serves CSS modules as the client's class-name map", () => {
  const app = realpathSync(mkdtempSync(join(tmpdir(), "oj-ssr-cssmod-")));

  try {
    const source = join(app, "src");
    const rolldown = join(app, "node_modules", "rolldown");
    for (const directory of [source, rolldown]) mkdirSync(directory, { recursive: true });

    writeFileSync(join(app, "package.json"), JSON.stringify({ name: "synthetic-cssmod-app", type: "module" }));
    writeFileSync(join(rolldown, "package.json"), JSON.stringify({
      name: "rolldown",
      type: "module",
      exports: { "./experimental": "./experimental.mjs" },
    }));
    writeFileSync(join(rolldown, "experimental.mjs"), "export const transformSync = (_path, code) => ({ code });\n");

    // The class set exercises kebab names, @keyframes, :global exclusion,
    // strings and url() noise. The hash depends only on the root-relative
    // path, so extra rules do not disturb the pinned values.
    writeFileSync(join(source, "Counter.module.css"), [
      '.button { color: red; background: url(dot.not-a-class.png); content: ".fake"; }',
      ".my-btn { color: blue; }",
      "@keyframes spin { to { transform: none; } }",
      ":global(.unscoped) { color: green; }",
      "#hdr { color: teal; }",
    ].join("\n"));
    writeFileSync(join(source, "app.module.scss"), ".card { padding: 1rem; }\n");
    writeFileSync(join(source, "plain.css"), ".anything { color: black; }\n");

    const entry = join(source, "entry.mjs");
    writeFileSync(entry, [
      'import counter from "./Counter.module.css";',
      'import card from "./app.module.scss";',
      'import plain from "./plain.css";',
      'import inlineCss from "./plain.css?inline";',
      "export default { counter, card, plain, inlineCss };",
    ].join("\n"));

    const runner = [
      'import { registerHooks } from "node:module";',
      `const loader = await import(${JSON.stringify(pathToFileURL(loader).href)});`,
      "registerHooks({ resolve: loader.resolve, load: loader.load });",
      `const result = await import(${JSON.stringify(pathToFileURL(entry).href)});`,
      "process.stdout.write(JSON.stringify(result.default));",
    ].join("\n");

    const result = spawnSync(process.execPath, ["--input-type=module", "--eval", runner], {
      encoding: "utf8",
      timeout: 10_000,
      env: { ...process.env, OJ_APP_ROOT: app, OJ_CACHE_ROOT: join(app, "cache"), OJ_SSR_LOADER_CACHE: "off" },
    });

    assert.equal(result.status, 0, result.stderr || result.error?.message);
    const { counter, card, plain, inlineCss } = JSON.parse(result.stdout);

    // Literals generated by oj_css (lightningcss) for these exact paths.
    assert.deepEqual(counter, {
      button: "Counter-module_button_EjW_Uq",
      "my-btn": "Counter-module_my-btn_EjW_Uq",
      spin: "Counter-module_spin_EjW_Uq",
      hdr: "Counter-module_hdr_EjW_Uq",
    });
    assert.deepEqual(card, { card: "app-module_card_r4GtOG" });

    // Plain (non-module) stylesheets keep the empty-object default.
    assert.deepEqual(plain, {});

    // ?inline on a stylesheet is css text (the client serves the compiled
    // string), not a data URL.
    assert.equal(inlineCss, ".anything { color: black; }\n");
  } finally {
    rmSync(app, { recursive: true, force: true });
  }
});
